// ═══════════════════════════════════════════
// VITAZEN — Premium Reflections Collection
// ═══════════════════════════════════════════
//
// Original reflections in the style of
// Robin Sharma / quiet discipline / clarity.
// No clichés. No toxic motivation. No copies.
// Brief, deep, calm. For VitaZen identity.

export const REFLECTIONS: readonly string[] = [
  // ─── Disciplina silenciosa ───
  'La disciplina no grita. La disciplina simplemente aparece cada día y hace lo que tiene que hacer.',
  'No necesitas sentirte motivado para hacer lo correcto. Solo necesitas empezar.',
  'La persona que quieres ser está al otro lado de la incomodidad que evitas.',
  'La consistencia no es espectacular. Pero la consistencia transforma.',
  'Lo que haces cuando nadie te ve define quién eres cuando todos te miran.',
  'La rutina no es una prisión. Es el marco donde la libertad se sostiene.',
  'Cada mañana eliges: la comodidad de lo conocido o la expansión de lo posible.',
  'La disciplina real no se fuerza. Se elige en silencio, una y otra vez.',
  'No esperes a tener ganas. Las ganas llegan después de empezar.',
  'El progreso real es silencioso. No necesita audiencia.',
  'Un pequeño acto de disciplina hoy es una semilla que el futuro agradece.',
  'La voluntad se agota. Los sistemas perduran. Diseña tu entorno.',
  'La diferencia entre quien eres y quien quieres ser es lo que haces cuando no tienes ganas.',
  'La excelencia no es un momento. Es una dirección.',
  'No se trata de ser perfecto. Se trata de no abandonar.',
  'La persona disciplinada no es la que más sufre, es la que más claro tiene lo que quiere.',
  'Cada hábito es un voto por la persona que decides ser.',
  'La fuerza no está en empezar con intensidad. Está en no parar.',
  'Lo fácil te hace débil. Lo difícil te construye. Elige con cuidado.',
  'La disciplina es el arte de recordar lo que realmente quieres.',

  // ─── Claridad mental ───
  'La claridad no llega pensando más. Llega eliminando lo innecesario.',
  'Una mente saturada no piensa. Solo reacciona.',
  'El ruido exterior calla cuando el interior se ordena.',
  'No necesitas más información. Necesitas más silencio.',
  'La respuesta que buscas no está en hacer más. Está en detenerte.',
  'Pensar con claridad es un acto de coraje. Significa soltar lo cómodo.',
  'La confusión no es falta de inteligencia. Es falta de prioridades.',
  'Antes de actuar, pregúntate: ¿esto me acerca a quien quiero ser?',
  'La mente clara no tiene prisa. Y no pierde tiempo.',
  'Simplificar es el acto más sofisticado de inteligencia.',
  'No hay claridad sin honestidad contigo mismo.',
  'La mente ordenada ve oportunidades donde la mente caótica ve problemas.',
  'Si no sabes qué hacer, haz una cosa sola. La claridad sigue a la acción.',
  'El primer paso hacia la claridad es admitir lo que no sabes.',
  'Donde hay confusión, hay algo que no quieres ver.',

  // ─── Presencia y calma ───
  'La calma no es ausencia de problemas. Es presencia ante ellos.',
  'El poder real no se demuestra con volumen. Se demuestra con quietud.',
  'Respira. No necesitas resolver todo ahora.',
  'La persona más fuerte en la sala es la que no necesita alzar la voz.',
  'Entre lo que pasa y tu reacción hay un espacio. Ahí vive tu libertad.',
  'La tranquilidad no se busca. Se practica hasta que se convierte en quien eres.',
  'No confundas movimiento con progreso. A veces lo más productivo es estar quieto.',
  'La presencia es el lujo que casi nadie se permite.',
  'El silencio no está vacío. Está lleno de respuestas.',
  'La persona calmada no ignora el caos. Lo observa sin ser arrastrada.',
  'Aprender a detenerte antes de reaccionar cambia todo.',
  'La paz no llega cuando los problemas desaparecen. Llega cuando tú dejas de luchar contra lo que no controlas.',
  'No necesitas meditar una hora. Necesitas una pausa consciente de verdad.',
  'La calma es contagiosa. Si tú la practicas, el entorno cambia.',
  'Observar sin juzgar es la habilidad más subestimada.',

  // ─── Enfoque y prioridades ───
  'El enfoque no es hacer más. Es decidir qué no hacer.',
  'Cada sí a lo irrelevante es un no a lo esencial.',
  'La persona enfocada no tiene más tiempo. Tiene menos distracciones.',
  'Di no a lo bueno para poder decir sí a lo extraordinario.',
  'Si todo es prioridad, nada lo es.',
  'La productividad sin dirección es solo actividad.',
  'Haz una cosa bien antes de intentar hacer diez.',
  'Tu atención es tu recurso más escaso. No lo regales.',
  'El foco es un músculo. Se entrena eligiendo una cosa y manteniéndote.',
  'La persona que domina su atención domina su vida.',
  'No necesitas más horas. Necesitas más decisiones claras.',
  'Cada distracción que aceptas es un pequeño abandono de tu propósito.',
  'Lo urgente rara vez es importante. Lo importante rara vez es urgente.',
  'Elige tres cosas. Hazlas bien. Lo demás puede esperar.',

  // ─── Propósito y dirección ───
  'Sin dirección, hasta el viento más favorable no te lleva a ningún sitio.',
  'El propósito no se encuentra. Se construye con decisiones repetidas.',
  'No necesitas un propósito grandioso. Necesitas una dirección honesta.',
  'La vida con propósito no es más fácil. Pero sí tiene más peso.',
  'Pregúntate: ¿por qué hago lo que hago? Si la respuesta no te convence, cambia.',
  'El propósito claro elimina la necesidad de motivación constante.',
  'Quien sabe para dónde va no necesita que le aplaudan.',
  'El propósito no es un destino. Es una brújula.',
  'No busques tu pasión. Construye tu competencia. La pasión sigue al dominio.',
  'La persona con propósito no compite. Se concentra.',
  'Un propósito pequeño y consistente supera a una pasión grande e intermitente.',
  'Si no sabes hacia dónde vas, cualquier camino parece correcto. Y ninguno lo es.',

  // ─── Crecimiento personal ───
  'El crecimiento no es cómodo. Pero la estancación duele más.',
  'No creces en la zona cómoda. Y no creces castigándote. Creces eligiendo lo difícil con amabilidad.',
  'La persona que dejaste de ser no es tu enemiga. Es tu punto de partida.',
  'Cada vez que eliges aprender en vez de defenderte, creces.',
  'El verdadero crecimiento empieza cuando dejas de pretender que lo sabes todo.',
  'No compares tu capítulo 3 con el capítulo 20 de alguien más.',
  'La evolución personal no tiene línea de meta. Solo tiene dirección.',
  'La humildad no es debilidad. Es la puerta de todo crecimiento real.',
  'Cae siete veces. Levántate ocho. No por obligación. Porque aún quieres.',
  'La versión futura de ti te agradece cada decisión difícil de hoy.',
  'Aprender a desaprender es la habilidad más difícil y la más valiosa.',
  'El crecimiento real duele porque exige soltar partes de ti que ya no sirven.',
  'No necesitas un evento transformador. Necesitas pequeñas decisiones diarias.',
  'La persona que crece nunca llega. Siempre está en camino.',

  // ─── Relación con uno mismo ───
  'La voz que más escuchas es la tuya. Elige lo que te dices.',
  'No eres tus pensamientos. Eres quien los observa.',
  'Trátate como tratarías a alguien que realmente te importa.',
  'La autocompasión no es debilidad. Es lo que te permite seguir.',
  'No necesitas ser otro. Necesitas dejar de esconderte.',
  'La autenticidad cuesta caro. Pero la máscara cuesta más.',
  'Tu valor no depende de tu productividad.',
  'Descansar no es rendirse. Es parte de la estrategia.',
  'La persona más importante con la que debes estar bien eres tú.',
  'Háblate como hablarías a tu mejor amigo en un mal día.',
  'Aceptarte no es conformarte. Es empezar desde la verdad.',
  'No te castigues por no saber lo que no pudiste aprender.',
  'La vulnerabilidad no es debilidad. Es la prueba de que estás vivo.',

  // ─── Bienestar y energía ───
  'Tu cuerpo es el vehículo de todo lo que quieres lograr. No lo ignores.',
  'Dormir bien no es un lujo. Es una estrategia de alto rendimiento.',
  'La energía se gestiona, no se busca.',
  'Un cuerpo cansado no produce ideas claras.',
  'Moverte no es entrenar. Es honrar el vehículo que te lleva.',
  'Lo que comes hoy afecta cómo piensas mañana.',
  'La hidratación, el sueño y el movimiento son las tres herramientas más subestimadas.',
  'No hay rendimiento sostenible sin descanso deliberado.',
  'Tu cuerpo siempre te habla. La pregunta es si estás escuchando.',
  'La vitalidad no es suerte. Es consecuencia de decisiones diarias.',
  'Cuidar tu energía no es egoísmo. Es inteligencia.',
  'El agotamiento no es medalla. Es señal de que algo está desalineado.',

  // ─── Mente y meditación ───
  'Meditar no es dejar de pensar. Es observar sin ser arrastrado.',
  'Diez minutos de silencio pueden cambiar la calidad de tu día entero.',
  'La mente sin entrenar es como un río sin orillas. Pone límites.',
  'No necesitas vaciar la mente. Necesitas dejar de luchar contra ella.',
  'La respiración consciente es la herramienta más accesible y la menos usada.',
  'Observar un pensamiento sin reaccionar cambia la dirección del día.',
  'La atención plena no es una técnica. Es una forma de estar.',
  'El espacio entre pensamiento y acción es donde vive tu libertad.',
  'La mente calmada ve lo que la mente agitada no puede.',
  'No necesitas una hora de meditación. Necesitas un momento de verdad.',
  'Cada vez que regresas a la respiración, entrenas la capacidad de elegir.',
  'El silencio interior no se compra. Se practica.',

  // ─── Finanzas y libertad ───
  'La libertad financiera empieza con un hábito, no con un salario.',
  'Cada euro que no gastas en lo innecesario es tiempo de libertad comprado.',
  'No necesitas ganar más. Necesitas decidir mejor.',
  'El dinero no es la meta. La tranquilidad sí.',
  'Ahorra no para tener más, sino para depender menos.',
  'La disciplina financiera refleja la disciplina mental.',
  'Invertir en ti mismo es la única inversión sin riesgo de pérdida.',
  'La abundancia empieza cuando dejas de comparar.',
  'Un presupuesto honesto es un espejo de tus prioridades.',
  'La riqueza real es no necesitar impresionar a nadie.',
  'Lo que compras con impulso lo pagas con tiempo futuro.',
  'La paciencia financiera genera las mayores recompensas.',

  // ─── Acción y movimiento ───
  'La acción cura el miedo. La inacción lo alimenta.',
  'No esperes a estar listo. La preparación llega haciendo.',
  'Hazlo mal, pero hazlo. La mejora llega después del inicio.',
  'Un paso imperfecto vale más que mil planes perfectos.',
  'La perfección es el enemigo más elegante del progreso.',
  'El momento perfecto no existe. El momento ahora es lo único real.',
  'La procrastinación no es pereza. Es miedo disfrazado.',
  'Empieza antes de sentirte seguro. La seguridad viene después.',
  'Cada acción pequeña es una declaración de quién decides ser.',
  'La persona que actúa mientras otros piensan siempre gana.',
  'No necesitas confianza para empezar. Necesitas empezar para tener confianza.',
  'El movimiento genera claridad. La quietud prolongada genera duda.',

  // ─── Tiempo y presencia ───
  'El tiempo no se gestiona. Se elige.',
  'Lo que haces con esta hora define lo que haces con tu vida.',
  'No tienes falta de tiempo. Tienes falta de prioridades claras.',
  'Cada minuto invertido en lo que no importa es un minuto robado a lo que sí.',
  'El presente es el único lugar donde algo puede cambiar.',
  'No pospongas lo importante para cuando tengas tiempo. El tiempo no llega solo.',
  'La forma en que usas tus mañanas predice la calidad de tus días.',
  'El tiempo pasa de todos modos. La pregunta es quién lo usa con intención.',
  'Estás aquí. Ahora. Eso es todo lo que necesitas para empezar.',
  'El futuro se construye con lo que haces en este momento exacto.',

  // ─── Resistencia y adversidad ───
  'La tormenta no pregunta si estás listo. Por eso conviene entrenar bajo sol.',
  'El dolor es temporal. El arrepentimiento es permanente.',
  'No eres lo que te pasa. Eres cómo respondes.',
  'La adversidad no te define. Te revela.',
  'Cada crisis es una pregunta: ¿quién decides ser ahora?',
  'La resiliencia no es aguantar en silencio. Es elegir seguir con intención.',
  'Las personas más fuertes no son las que nunca caen. Son las que siempre se levantan.',
  'Lo difícil no es pasar por la tormenta. Es mantener la dirección mientras tanto.',
  'La incomodidad temporal es el precio de la libertad permanente.',
  'No necesitas ver todo el camino. Solo el siguiente paso.',

  // ─── Soltar y simplicidad ───
  'Soltar no es rendirse. Es hacer espacio para lo que importa.',
  'Menos decisiones, más profundidad. La simplicidad es poder.',
  'Lo que no usas, lo que no necesitas, lo que no te nutre: suéltalo.',
  'La vida ligera no es vida vacía. Es vida sin lastre.',
  'No añadas. Elimina. La elegancia está en lo esencial.',
  'Cada cosa que posees también te posee. Elige con cuidado.',
  'La simplicidad no es pobreza. Es claridad.',
  'Aprende a soltar lo que ya no te representa.',
  'El orden exterior es el reflejo del orden interior.',
  'Menos ruido. Más señal.',

  // ─── Reflexiones profundas ───
  'La persona que te miras al espejo por la mañana es la que tienes que convencer.',
  'Todo lo que evitas te sigue. Todo lo que enfrentas te libera.',
  'No busques significado. Constrúyelo.',
  'La madurez es aceptar que no todo tiene solución inmediata.',
  'La vida no te debe nada. Tú le debes a la vida tu mejor versión.',
  'La pregunta más importante no es qué hacer. Es por qué hacerlo.',
  'No vives en las circunstancias. Vives en tu interpretación de ellas.',
  'Lo que toleras persiste. Lo que confrontas se transforma.',
  'La sabiduría no es saber más. Es necesitar menos.',
  'La verdadera transformación empieza cuando dejas de buscar atajos.',
  'No eres lo que te ocurre. Eres lo que decides hacer con ello.',
  'La libertad más grande es elegir tu actitud cuando no puedes elegir tus circunstancias.',
  'Cada día es una versión nueva de ti. ¿Cuál eliges hoy?',
  'La profundidad no se encuentra en las respuestas. Se encuentra en las preguntas correctas.',
  'Lo que no se examina se repite.',

  // ─── Mañana y comienzos ───
  'Cada amanecer es una invitación a empezar de nuevo. No la desperdicies.',
  'La primera hora del día define la dirección de las demás.',
  'Despierta con un propósito, no con una alarma.',
  'La mañana no es para reaccionar. Es para crear.',
  'Antes de abrir el teléfono, ábrete a ti mismo.',
  'Un inicio consciente cambia la trayectoria de todo el día.',
  'La persona que domina sus mañanas domina su vida.',
  'No dejes que el mundo entre antes de que tú hayas decidido quién eres hoy.',
  'El primer pensamiento del día importa más que el último de ayer.',
  'Tu mejor momento es ahora. No ayer. No mañana. Ahora.',

  // ─── Silencio e interioridad ───
  'El silencio no es ausencia. Es presencia profunda.',
  'Hablar menos, observar más. Ese es el camino.',
  'La persona que domina el silencio domina las palabras.',
  'No necesitas responder a todo. A veces, la pausa es la respuesta.',
  'El mundo habla demasiado. El sabio escucha.',
  'En el silencio encuentras lo que el ruido te roba.',
  'El silencio interior es el verdadero lujo moderno.',
  'Quien se escucha a sí mismo no necesita la aprobación de nadie.',
  'La profundidad requiere silencio. La prisa te mantiene en la superficie.',
  'Haz silencio. La respuesta vendrá.',

  // ─── Integridad y carácter ───
  'La integridad es lo que haces cuando nadie observa.',
  'Tu palabra es tu moneda más valiosa. No la devalúes.',
  'El carácter no se construye en la comodidad. Se forja en la decisión difícil.',
  'Haz lo correcto, no lo fácil. Es la única inversión que nunca pierde.',
  'La congruencia entre lo que piensas, dices y haces es la definición de fuerza.',
  'No pierdas tu paz para ganar una discusión.',
  'La persona íntegra no necesita defenderse. Su vida habla.',
  'Tu reputación es lo que otros piensan. Tu carácter es lo que tú sabes.',
  'Las promesas pequeñas mantenidas construyen una vida grande.',
  'La verdad no siempre es cómoda, pero siempre es libre.',

  // ─── Coraje y vulnerabilidad ───
  'El coraje no es ausencia de miedo. Es la decisión de avanzar a pesar de él.',
  'Ser vulnerable no es débil. Es la forma más honesta de ser fuerte.',
  'El miedo no desaparece. Se convierte en compañero de camino.',
  'Hacer lo que te da miedo una vez al semana cambia tu vida.',
  'La zona segura es confortable. Pero nada crece ahí.',
  'No necesitas ser valiente siempre. Solo en el momento que importa.',
  'La persona que admite su miedo ya ha dado el primer paso.',
  'La vulnerabilidad es el precio de la conexión real.',
  'No dejes que el miedo a fallar te robe la oportunidad de crecer.',
  'El coraje silencioso de cada día es más heroico que cualquier gesto espectacular.',

  // ─── Aprendizaje y curiosidad ───
  'Aprender algo nuevo cada día es la inversión con mejor interés.',
  'La curiosidad mantiene joven la mente y abierta el alma.',
  'El que cree que ya sabe ha dejado de crecer.',
  'Cada persona que conoces sabe algo que tú no.',
  'El error no es lo contrario del aprendizaje. Es parte de él.',
  'La mente abierta no es debilidad. Es la puerta de toda posibilidad.',
  'Lee. Reflexiona. Aplica. Repite.',
  'El conocimiento sin acción es entretenimiento. La acción sin conocimiento es riesgo.',
  'Desaprender es más difícil que aprender. Y más necesario.',
  'La mejor pregunta no es qué sé. Es qué me falta por entender.',

  // ─── Gratitud y perspectiva ───
  'La gratitud no cambia las circunstancias. Cambia quien las observa.',
  'Lo que tienes ahora una vez fue lo que esperabas.',
  'Agradecer no es conformarse. Es reconocer para poder crecer.',
  'La perspectiva cambia todo: lo que parece problema puede ser lección.',
  'No necesitas más para ser feliz. Necesitas notar lo que ya tienes.',
  'La gratitud es la disciplina más simple y la más transformadora.',
  'Antes de pedir más, reconoce lo que ya es.',
  'Ver lo que tienes con claridad es el primer paso para construir lo que quieres.',
  'La persona agradecida no tiene más. Simplemente ve más.',
  'Cada día tiene algo que agradecer. Incluso los difíciles. Especialmente los difíciles.',
] as const;
