// ═══════════════════════════════════════════
// Etapas — Observations
// ═══════════════════════════════════════════
//
// Generates calm human observations from accumulated data.
// NOT AI. NOT coaching. NOT analytics.
// Only intelligent, sober logic from real data.
//
// If insufficient data: nothing is invented.
// ═══════════════════════════════════════════

import { db } from '@/lib/db';
import type { LifeStage, StageTransition } from './stages';

// ─── Types ───

export interface LifeMemoryObservation {
  id: string;
  text: string;
  type: 'stage' | 'transition' | 'memory' | 'pattern';
  month?: string;
  monthLabel?: string;
  empires?: string[];
}

export interface HighlightedMemory {
  text: string;
  date: string;
  empire: string;
}

// ─── Generate observations from stages ───

export function observationsFromStages(stages: LifeStage[]): LifeMemoryObservation[] {
  return stages
    .filter(s => s.dataPoints >= 1) // Any data is meaningful — "quiet" stages (dataPoints < 3) are valid
    .map(s => ({
      id: `stage-${s.month}`,
      text: s.observation,
      type: 'stage' as const,
      month: s.month,
      monthLabel: s.monthLabel,
    }));
}

// ─── Generate observations from transitions ───

export function observationsFromTransitions(transitions: StageTransition[]): LifeMemoryObservation[] {
  return transitions
    .filter(t => t.observation.length > 0)
    .map(t => ({
      id: `transition-${t.month}`,
      text: t.observation,
      type: 'transition' as const,
      month: t.month,
      monthLabel: t.monthLabel,
    }));
}

// ─── Highlighted memories ───
// Real human moments from contexto, journal, checkin notes.
// NOT invented. NOT generated by AI.

export async function getHighlightedMemories(userId: string, months: string[]): Promise<HighlightedMemory[]> {
  const memories: HighlightedMemory[] = [];

  // Get date range from months
  if (months.length === 0) return memories;

  const startStr = months[0];
  const endStr = months[months.length - 1];
  const [startYear, startMonth] = startStr.split('-').map(Number);
  const [endYear, endMonth] = endStr.split('-').map(Number);
  const start = new Date(startYear, startMonth - 1, 1);
  const end = new Date(endYear, endMonth, 1);

  // Finance logs with contexto (most human)
  const financeWithCtx = await db.financeLog.findMany({
    where: {
      userId,
      date: { gte: start, lt: new Date(end.getFullYear(), end.getMonth() + 1, 1) },
      contexto: { not: null },
    },
    select: { contexto: true, date: true, category: true, mood: true },
    orderBy: { date: 'desc' },
    take: 5,
  });

  for (const f of financeWithCtx) {
    if (f.contexto && f.contexto.trim().length > 5) {
      memories.push({
        text: f.contexto,
        date: f.date.toISOString(),
        empire: 'Finanzas',
      });
    }
  }

  // Journal entries
  const journals = await db.journalEntry.findMany({
    where: {
      userId,
      createdAt: { gte: start, lt: new Date(end.getFullYear(), end.getMonth() + 1, 1) },
    },
    select: { title: true, content: true, createdAt: true },
    orderBy: { createdAt: 'desc' },
    take: 3,
  });

  for (const j of journals) {
    memories.push({
      text: j.content ? j.content.slice(0, 120) + (j.content.length > 120 ? '...' : '') : j.title,
      date: j.createdAt.toISOString(),
      empire: 'Mente',
    });
  }

  // Checkin notes with substance
  const checkinNotes = await db.dailyCheckin.findMany({
    where: {
      userId,
      date: { gte: start, lt: new Date(end.getFullYear(), end.getMonth() + 1, 1) },
      note: { not: null },
    },
    select: { note: true, date: true },
    orderBy: { date: 'desc' },
    take: 3,
  });

  for (const c of checkinNotes) {
    if (c.note && c.note.trim().length > 5) {
      memories.push({
        text: c.note,
        date: c.date.toISOString(),
        empire: 'General',
      });
    }
  }

  // Sort by date, oldest first (for timeline feel)
  memories.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  return memories.slice(0, 10);
}

// ─── Pattern observations (using existing pattern API) ───
// The pattern detection is done by the existing /api/patterns route.
// We call it from the frontend, not here, to avoid duplicating the
// data assembly logic. This function is a placeholder that gets
// populated by the API response.

export interface PatternObservationData {
  id: string;
  text: string;
  empires: string[];
}

export function observationsFromPatterns(patterns: PatternObservationData[]): LifeMemoryObservation[] {
  return patterns.map((obs, i) => ({
    id: `pattern-${obs.id || i}`,
    text: obs.text,
    type: 'pattern' as const,
    empires: obs.empires,
  }));
}

// ─── Combine all observations into a timeline ───

export interface LifeMemoryTimeline {
  observations: LifeMemoryObservation[];
  memories: HighlightedMemory[];
  hasEnoughData: boolean;
  totalMonths: number;
  oldestMonth: string | null;
  newestMonth: string | null;
}

export function buildTimeline(
  stages: LifeStage[],
  transitions: StageTransition[],
  memories: HighlightedMemory[],
  patternObs: LifeMemoryObservation[],
  months: string[],
): LifeMemoryTimeline {
  const stageObs = observationsFromStages(stages);
  const transitionObs = observationsFromTransitions(transitions);

  // Combine and sort by month
  const allObservations = [...stageObs, ...transitionObs, ...patternObs]
    .sort((a, b) => {
      // Stage and transition observations are ordered by month
      if (a.month && b.month) return a.month.localeCompare(b.month);
      // Pattern observations go at the end (current)
      if (!a.month) return 1;
      if (!b.month) return -1;
      return 0;
    });

  const hasEnoughData = stages.length >= 2 || memories.length >= 3;

  return {
    observations: allObservations,
    memories,
    hasEnoughData,
    totalMonths: months.length,
    oldestMonth: months.length > 0 ? months[0] : null,
    newestMonth: months.length > 0 ? months[months.length - 1] : null,
  };
}
